host: localhost
port: 8080
password: qazxsw
"server-password": password
user: user1
SelfName: You
SelfColor: "null"
date-format: DD/MM/RRRR hh:mm:ss
sound: false
# RRRR - year
# MM - month
# DD - day
# hh - hour
# mm - minute
# ss - second