port: 8080
server-password: password
allowed-users:
  - user: user1
    password: qazxsw
  - user: user2
    password: wsxzaq
private: true
anyone-can-join: false
max-users: 10
motd: Example motd. Lorem ipsum coś tam dalej xd
"server-color": "#00FF00"